### ISSUE TITLE
drawing curves - arc? bezier? half circle?

### ISSUE THREAD

**Issue by yejinkay** [cdaein/mica-gd405#2]
So I'm trying to make an "O"
<img width="459" alt="screen shot 2019-02-16 at 7 58 42 pm" src="https://user-images.githubusercontent.com/46943898/52906957-4ee01d80-3225-11e9-9f62-b15b7afd1435.png">
but I'm having problem making 
<img width="412" alt="screen shot 2019-02-16 at 7 58 46 pm" src="https://user-images.githubusercontent.com/46943898/52906959-53a4d180-3225-11e9-95af-193fd06cdc49.png">
 to be honest I don't know where to start but i've tried to use 

```
void drawO(float x, float y){
  
  beginShape();
  bezier(0+x,30+y,0+x,15+y,20+X,0+y,40+x,0+y);
  bezier(40+x,0+y,60+x,0+y,80+x,13+y,80+x,30+y);
  line(80+x,30+y,60+x,30+y);
  bezier(60+x,30+y,60+x,20+y,50+x,20+y,40+x,20+y);
  bezier(40+x,20+y,30+x,20+y,20+x,20+y,20+x,30+y);
  line(20+x,30+y,0+x,30+y);
  endShape();
  
}
```

but I ended up getting 
<img width="264" alt="screen shot 2019-02-16 at 8 00 28 pm" src="https://user-images.githubusercontent.com/46943898/52906973-8bac1480-3225-11e9-8089-1dc996973c3d.png">

Is there a better way to make this shape? 
Since this is not a perfect half circle I'm not sure where to start with this shape. 

Thank you in advance!

**Comment by sangwooHahn** [comment]
<img width="725" alt="2019-02-16 8 21 31" src="https://user-images.githubusercontent.com/46931287/52907111-7389c480-3228-11e9-9ac6-aaac860134d8.png">

**Comment by sangwooHahn** [comment]
<img width="710" alt="2019-02-16 8 25 38" src="https://user-images.githubusercontent.com/46931287/52907140-06c2fa00-3229-11e9-8b3f-721673efe77e.png">

**Comment by cdaein** [comment]
Thank you, Sangwoo for the really nice illustration. This will work to make sure it will become a single shape as well as finding the right order of numbers.

With `bezier()`, you can only create a bezier "segment" - it will not connect to other points and lines.
For complex shapes that have curves/straight lines in a single shape, you have to use `beginShape()` and `endShape()` as well as `bezierVertex()`(instead of simple `bezier()`). Otherwise, you won't be able to fill in the shape with black.

The other problem is how to get the right coordinates for defining bezier vertices. As we discussed in class, you can use Info panel in Illustrator to get the rough coordinate values. If you want to do it more properly, here is a workaround:

Install *AI2Canvas* plug-in for Adobe Illustrator. You can find how-to-use videos on Youtube. This plugin converts Illustrator shape into HTML5 Canvas code, but you don't need to know how to use Canvas code. The code looks very similar to Processing. Simply, change `moveTo()` and `lineTo()` to `vertex()`. Change `bezierCurveTo()` to `bezierVertex()`.
