### ISSUE TITLE
Can't use the pdf file

### ISSUE THREAD

**Issue by rrodriguezsandchez** [cdaein/mica-gd405#3]
I can not seem to use the PDF file this creates for some reason.
<img width="831" alt="screen shot 2019-03-04 at 5 40 44 pm" src="https://user-images.githubusercontent.com/46931252/53770414-f22f6480-3eac-11e9-9238-d57ef7ca5b02.png">

**Comment by yejinkay** [comment]
Well in order to save it as .pdf you need to first add beginRecord() and endRecord() functions. Otherwise the program won't know where to start and end to export to pdf. 

You put beginRecord(PDF,"render.pdf"); in your void setup() after your size. and then endRecord(); in your void keyPressed(). 

I hope that helped! Let me know if you're not getting it. 

Here's a reference from one of the tutorial videos.


<img width="601" alt="screen shot 2019-03-04 at 6 55 44 pm" src="https://user-images.githubusercontent.com/46943898/53771052-30c61e80-3eaf-11e9-8cbf-e84c6bc3629e.png">

**Comment by rrodriguezsandchez** [comment]
That worked thank you!!!

**Comment by cdaein** [comment]
@yejinkay 's solution will work great if you want to record multiple frames into your PDF. (ie. some animation accumulated into a single image). If you open the PDF in Illustrator, you may end up with a lot of duplicate shapes.

If you want to just capture a *single* frame of your sketch in your PDF, you need a different structure. Go to `File > Examples...` and under `PDF export` and find `MousePress` example, and compare the differences.
