### ISSUE TITLE
Messed up translate??

### ISSUE THREAD

**Issue by rrodriguezsandchez** [cdaein/mica-gd405#4]
<img width="1369" alt="Screen Shot 2019-03-09 at 7 32 09 PM" src="https://user-images.githubusercontent.com/46931252/54079036-1a023c00-42a2-11e9-947c-8c4b602abadb.png">
<img width="1002" alt="Screen Shot 2019-03-09 at 7 31 52 PM" src="https://user-images.githubusercontent.com/46931252/54079038-1bcbff80-42a2-11e9-9bc9-33399aaa6415.png">
<img width="1022" alt="Screen Shot 2019-03-09 at 7 31 43 PM" src="https://user-images.githubusercontent.com/46931252/54079039-1c649600-42a2-11e9-9bd5-d227cf905720.png">
I am trying just to  center this box in my feild.

**Comment by sangwooHahn** [comment]
This is because the top left is the starting point.
top-left corner is (x, y) position.
You can tried (x-w/2 , y-h/2);
or
used rectMode(CENTER);
it make rect change it to start with middle.

https://processing.org/reference/rectMode_.html
rectMode(CENTER) interprets the first two parameters of rect() as the shape's center point, while the third and fourth parameters are its width and height.
